name: Publish wiki folder to GitHub Wiki

# Trigger this action only if there are changes pushed to the docs/** directory under the main branch
on:
  push:
    paths:
      - wiki/** # This includes all sub folders
    branches:
      - main # This can be changed to any branch of your preference

env:
  USER_TOKEN: ${{ secrets.WIKI_ACTION_TOKEN }} # This is the repository secret
  USER_NAME: <USERNAME> # Enter the username of your (bot) account
  USER_EMAIL: <EMAIL> # Enter the e-mail of your (bot) account
  OWNER: ${{ github.event.repository.owner.name }} # This is the repository owner
  REPOSITORY_NAME: ${{ github.event.repository.name }} # This is the repository name

jobs:
  publish_docs_to_wiki:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2

      # 1. Create folder named `tmp_wiki`
      # 2. Initialize Git
      # 3. Pull old Wiki content

    - name: Pull wiki
      run: |
         mkdir tmp_wiki
         cd tmp_wiki
         git init
         git config user.name $USER_NAME
         git config user.email $USER_EMAIL
         git pull https://$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git

      # 4. Synchronize differences between `docs` & `tmp_wiki`
      # 5. Push new Wiki content

    - name: Push wiki
      run: |
        rsync -av --delete wiki/ tmp_wiki/ --exclude .git
        cd tmp_wiki
        git add .
        git commit -m "Update Wiki content"
        git push -f --set-upstream https://$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git master
